spring.datasource.url=jdbc:postgresql://localhost:5432/lost_and_found_system
spring.datasource.username=postgres
spring.datasource.password=16083
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.mongodb.uri=mongodb+srv://lostandfound:xDtSsFrDMnDfEKNH@cluster0.hlonqmk.mongodb.net/lostandfound_logs?retryWrites=true&w=majority
spring.rabbitmq.host=capybara.lmq.cloudamqp.com
spring.rabbitmq.port=5671
spring.rabbitmq.username=rbkhlkfp
spring.rabbitmq.password=kkza4fLy-4AxHlKSkDBkl_pAWU_XG8kA
spring.rabbitmq.virtual-host=rbkhlkfp
spring.rabbitmq.ssl.enabled=true
server.port=8081